version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.8.0
 
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run django tests
          command: |
            pip install pytest
            python a.py
      #      pytest
      # - store_test_results:
      #     path: test-results
      # - store_artifacts:
      #     path: test-results
      #     destination: tr1