version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.8.0
 
    steps:
      - checkout
      - run:
          name: Run django tests
          command: |
            pip install pytest
            py.test a.py
