version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.8.0
 
    steps:
      - checkout
      - run:
          name: Run django tests
          command: |
            pip install pytest
            py.test a.py

# version: 2.1

# # orb 是 CircleCI 特有的
# # 可以把 orb 想成已經打包好的環境
# # 跟 DockerHub 上的 docker image 很像
# orbs:
#   python: circleci/python@0.2.1

# jobs:
#   # 第一個 job，負責執行`測試`
#   build-and-test:
#     executor: python/default
#     steps:
#       - checkout

 	  # 為了增加 build 的速度，所設定的暫存
#       - restore_cache:
#           key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
			
 	  # 執行 python 虛擬環境，並安裝相依套件
#       - run:
#           command: |
#             python3 -m venv venv
#             . venv/bin/activate
#             pip install -r requirements.txt

 	  # 為了增加 build 的速度，所設定的暫存
#       - save_cache:
#           key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
#           paths:
#             - "venv"

 	  # 所有測試跑起來
#       - run:
#           name: Running tests
#           command: |
#             . venv/bin/activate
#             python3 manage.py test
#       - store_artifacts:
#           path: test-reports/
#           destination: python_app
#       - persist_to_workspace:
#           root: .
#           paths:
#             - build-and-text
#             - app.yaml

#   # 第二個 job 負責執行`部屬`
#   deploy:
#     # 採用官方的 docker image 可以省麻煩
#     docker:
#       - image: google/cloud-sdk
#     executor: python/default
#     steps:
 	  # 別忘了加 `checkout`，
 	  # 是為了讓 deploy 這個 job
 	  # 也能拿到目錄下的檔案
#       - checkout

 	  # 授權 gcloud，注意 CircleCI 的環境變數
#       - run:
#           name: Authorizing gcloud
#           command: |
#             echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account django-shop-269303@appspot.gserviceaccount.com --key-file=-
#             gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
#             gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}

 	  # 執行 GAE 的 deploy 指令
#       - run:
#           name: Deploy to App Engine
#           command: |
#             gcloud app deploy

# workflows:
#   main:
#     jobs:
#       - build-and-test
#       - deploy:
 		  # 表示 `build-and-test` 這個 job
 	      # 執行成功後，才會執行 `deploy` 的 job
#           requires:
#             - build-and-test