version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.8.0
 
    steps:
      - checkout
      - python/install-packages
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Run django tests
          command: |
            pip install pytest
            py.test a.py
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      #      pytest
      # - store_test_results:
      #     path: test-results
      # - store_artifacts:
      #     path: test-results
      #     destination: tr1